# 1.2 Линейная алгебра: аппроксимация функций

Рассмотрим сложную математическую функцию на отрезке [1, 15]:

f(x) = sin(x / 5) * exp(x / 10) + 5 * exp(-x / 2)

Сформируйте систему линейных уравнений (то есть задайте матрицу коэффициентов A и свободный вектор b) для многочлена первой степени, который должен совпадать с функцией f в точках 1 и 15. Решите данную систему с помощью функции scipy.linalg.solve. 

In [1]:
import numpy as np
import scipy.linalg
from numpy import sin, exp

In [2]:
f_x = lambda x: sin(x / 5.0) * exp(x / 10.0) + 5 * exp(-x / 2.0)

In [3]:
import matplotlib.pyplot as plt



In [4]:
polynom_rank = 1
A_1 = [
    [1 ** n for n in range(0, polynom_rank + 1)],
    [15 ** n for n in range(0, polynom_rank + 1)]
]

b_1 = [f_x(1), f_x(15)]

In [5]:
scipy.linalg.solve(A_1, b_1)

array([ 3.43914511, -0.18692825])

Повторите те же шаги для многочлена второй степени, который совпадает с функцией f в точках 1, 8 и 15. 

In [6]:
polynom_rank = 2
A_2 = [
    [1 ** n for n in range(0, polynom_rank + 1)],
    [8 ** n for n in range(0, polynom_rank + 1)],
    [15 ** n for n in range(0, polynom_rank + 1)]
]

b_2 = [f_x(1), f_x(8), f_x(15)]

scipy.linalg.solve(A_2, b_2)



array([ 3.32512949, -0.06531159, -0.00760104])

Повторите те же шаги для многочлена третьей степени, который совпадает с функцией f в точках 1, 4, 10 и 15. 

In [7]:
polynom_rank = 3
A_3 = [
    [1 ** n for n in range(0, polynom_rank + 1)],
    [4 ** n for n in range(0, polynom_rank + 1)],
    [10 ** n for n in range(0, polynom_rank + 1)],
    [15 ** n for n in range(0, polynom_rank + 1)]
]

b_3 = [f_x(1), f_x(4), f_x(10), f_x(15)]

scipy.linalg.solve(A_3, b_3)

array([ 4.36264154, -1.29552587,  0.19333685, -0.00823565])